### ISSUE TITLE
You just copied the official PyTorch SRCNN example.

### ISSUE THREAD

**Issue by reangdeba** [basher666/pytorch_srcnn#3]

**Comment by kawaiibilli** [comment]
Hey Debashish. I wrote this code by consulting various sources of SRCNN implementation and generic pytorch projects that was available online at the time of writing. It was at the time I started learning PyTorch and this was one of my very first PyTorch codes. Thanks for bringing it to my notice that I did not give credit to the proper sources. Apologies.
